### ADD TO CART
POST https://api-ppb.vercel.app/api/carts
Accept: application/json
Content-Type: application/json

{
  "user_id": 1,
  "product_id" : 3,
  "jumlah": 3
}


### GET KERANJNAG SAAT INI
POST https://api-ppb.vercel.app/api/carts/user
Accept: application/json
Content-Type: application/json

{
  "user_id": 1
}

### REMOVE
POST https://api-ppb.vercel.app/api/carts/remove
Accept: application/json
Content-Type: application/json

{
  "user_id": 4,
  "product_id" : 2
}


### ADD SHIPING TO GET RECIPT
POST https://api-ppb.vercel.app/api/carts/add-shipping
Accept: application/json
Content-Type: application/json

{
  "user_id": 1,
  "kota_asal": "Jakarta",
  "kota_tujuan": "Bandung",
  "biaya_ongkir": 25000,
  "weight": 5.0
}


### VALIDATE PAYMENT
POST https://api-ppb.vercel.app/api/carts/checkout
Accept: application/json
Content-Type: application/json

{
  "user_id": 1,
  "is_paid": true
}