### GET ALL
GET https://api-ppb.vercel.app/api/products
Accept: application/json
Content-Type: application/json

### GET BY ID
GET https://api-ppb.vercel.app/api/products/1
Accept: application/json
Content-Type: application/json

### CREATE ALL PRODUCT
POST https://api-ppb.vercel.app//api/products
Accept: application/json
Content-Type: application/json

{
  "name": "Kamera Digital Canon EOS 90D",
  "description": "Kamera DSLR dengan sensor 32.5MP dan kemampuan rekam video 4K.",
  "price": 15000000.00,
  "imageUrl": "https://example.com/canon-eos-90d.jpg"
}

### UPDATE
PUT https://api-ppb.vercel.app/api/products/1
Accept: application/json
Content-Type: application/json

{
  "name": "Laptop Gaming Banget",
  "description": "Laptop gaming dengan performa tinggi untuk bermain game berat.",
  "price": 15000000.50,
  "imageUrl": "https://example.com/laptop-xyz.jpg"
}

### DELETE
DELETE https://api-ppb.vercel.app/api/products/1
Accept: application/json
Content-Type: application/json


###
GET https://api-ppb.vercel.app/api/users
Accept: application/json
Content-Type: application/json

###
DELETE https://api-ppb.vercel.app/api/users/20
Accept: application/json
Content-Type: application/json

###
GET https://api-ppb.vercel.app/api/carts/history
Accept: application/json
Content-Type: application/json

###
GET https://api-ppb.vercel.app/api/carts/history/user/1
Accept: application/json
Content-Type: application/json

###
POST https://api-ppb.vercel.app/api/carts/history
Accept: application/json
Content-Type: application/json

{
  "start_date": "2025-01-01",
  "end_date": "2025-01-10"
}

###
POST http://localhost:3000/api/carts/history
Accept: application/json
Content-Type: application/json

{
  "start_date": "2025-01-01",
  "end_date": "2025-01-10"
}

