### CREATE ALL user
POST https://api-ppb.vercel.app/api/users
Accept: application/json
Content-Type: application/json

{
  "user": "John Doe",
  "username": "johndoe123",
  "password": "securePassword123",
  "role": "admin"
}

###
PUT https://api-ppb.vercel.app/users/1
Accept: application/json
Content-Type: application/json

{
  "user": "John Doe Dll",
  "username": "johndoe123",
  "password": "securePassword123",
  "role": "admin"
}

###
POST https://api-ppb.vercel.app/api/users/login
Accept: application/json
Content-Type: application/json

{
  "username": "aa",
  "password": "aa"
}


